@startuml iphone

interface ReprodutorMusical {
    +tocar(): void
    +pausar(): void
    +selecionarMusica(musica: String): void
}

interface AparelhoTelefonico {
    +ligar(numero: String): void
    +atender(): void
    +iniciarCorreioVoz(): void
}

interface NavegadorInternet {
    +exibirPagina(url: String): void
    +adicionarNovaAba(): void
    +atualizarPagina(): void
}

class Smartphone {
    +tocar(): void
    +pausar(): void
    +selecionarMusica(musica: String): void
    +ligar(numero: String): void
    +atender(): void
    +iniciarCorreioVoz(): void
    +exibirPagina(url: String): void
    +adicionarNovaAba(): void
    +atualizarPagina(): void
}

Smartphone ..|> ReprodutorMusical
Smartphone ..|> AparelhoTelefonico
Smartphone ..|> NavegadorInternet

@enduml
